spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/secure_shop?currentSchema=order_schema
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=order_schema
spring.jpa.show-sql=true

spring.flyway.schemas=order_schema
spring.flyway.default-schema=order_schema
