spring.application.name=product-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/secure_shop?currentSchema=product_schema
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=product_schema
spring.jpa.show-sql=true

spring.flyway.schemas=product_schema
spring.flyway.default-schema=product_schema

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/secure-shop
